<!DOCTYPE html>
<html lang="en">
    <head>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
		
		<meta name="description" content="">
		<meta name="author" content="">
		
        <title>Phalcon Bootstrap</title>
		
		<link rel="stylesheet" href="/css/vendor.css">
		<link rel="stylesheet" href="/css/main.css">
		
		<!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
		<!--[if lt IE 9]>
		<script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
		<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
		<![endif]-->
    </head>
	
    <body role="document">
		<?php $this->partial("partials/navbar"); ?>
		<div class="container" role="main">
			<?php echo $this->getContent(); ?>
		</div>
    </body>
	
	<script type="text/javascript" src="/js/vendor.js"></script>
	<script type="text/javascript" src="/js/main.js"></script>
</html>
